name: Deploy React Vite to Azure VM

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout code từ GitHub
            - name: Checkout code
              uses: actions/checkout@v3

            # Thiết lập SSH để kết nối với Azure VM
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}

            
            - name: Deploy to Azure VM
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << EOF
                    cd /var/www/pbl4-video-chat-fe
                    sudo git pull origin main
                    npm install --legacy-peer-deps
                    npm run build
                  EOF
