name: Deploy React Vite to EC2

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies and build
              run: |
                  npm install
                  npm run build

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/pbl4-fe:latest .

            - name: Push Docker image to Docker Hub
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/pbl4-fe:latest
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  script: |
                      # Pull the latest Docker image
                      docker pull ${{ secrets.DOCKER_USERNAME }}/pbl4-fe:latest

                      # Tạo file .env từ GitHub Secrets
                      echo "${{ secrets.ENV_FILE }}" > /home/${{ secrets.EC2_USER }}/.env

                      # Xóa image cũ nếu có
                      docker image prune -f || true

                      # Dừng và xóa container cũ nếu có
                      docker stop pbl4-fe-container || true
                      docker rm pbl4-fe-container || true

                      # Chạy container mới
                      docker run --rm -d \
                        -p 5173:80 -p 5174:443 \
                        --name pbl4-fe-container \
                        --env-file /home/${{ secrets.EC2_USER }}/.env \
                        -v /etc/nginx/ssl:/etc/nginx/ssl:ro \
                        ${{ secrets.DOCKER_USERNAME }}/pbl4-fe:latest
                      docker ps
